### ISSUE TITLE
Welcomer error

### ISSUE THREAD

**Issue by Waspyeh** [Repulser/bursting-cogs#12]
[04/04/2017 23:18] ERROR red on_command_error 374: Exception in command 'welcomer status'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Zgame\DM\Red-DiscordBot\cogs\welcomer.py", line 61, in status
    e.add_field(name="Join Toggle:", value=db[server.id]["Join"])
KeyError: 'Join'

**Comment by Repulser** [comment]
Give the latest commit a shot.
