### ISSUE TITLE
Error in command 'modlogtoggle delete' - KeyError: '237970672272408577'

### ISSUE THREAD

**Issue by GhostSquad57** [Repulser/bursting-cogs#6]
Whenever I try to toggle anything from modlogtoggle, it gives me the following erorr:
`Error in command 'modlogtoggle delete' - KeyError: '237970672272408577'`

Python output:
```
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hal9000/apps/hal/cogs/modlog.py", line 151, in ban
    if db[server.id]["toggleban"] == False:
KeyError: '237970672272408577'
[03/02/2017 02:16] ERROR red on_command_error 363: Exception in command 'modlogtoggle delete'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hal9000/apps/hal/cogs/modlog.py", line 95, in delete
    if db[server.id]["toggledelete"] == False:
KeyError: '237970672272408577'
```

**Comment by Repulser** [comment]
You need to modlogset channel

**Comment by Jonny0181** [comment]
You need to do [p]modlogset channel in the channel you want to modlog in. Just like Repulser said above.

**Comment by GhostSquad57** [comment]
Tested it out and I can confirm this was the issue. Thanks!
